/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author augus
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    private MainForm mainForm;
    
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        super("Login");
        initComponents();
        this.setSize(600,400);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.mainForm = new MainForm();
    }
    
    public LoginForm(MainForm mainForm) {
        initComponents();
        this.mainForm = mainForm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_ipReuniao = new javax.swing.JLabel();
        jLabel_porta = new javax.swing.JLabel();
        jLabel_nickname = new javax.swing.JLabel();
        jTextField_ipReuniao = new javax.swing.JTextField();
        jTextField_porta = new javax.swing.JTextField();
        jTextField_nickname = new javax.swing.JTextField();
        jButton_entrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_ipReuniao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_ipReuniao.setText("IP da Reunião");

        jLabel_porta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_porta.setText("Porta");

        jLabel_nickname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_nickname.setText("Nickname");

        jTextField_ipReuniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ipReuniaoActionPerformed(evt);
            }
        });

        jButton_entrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_entrar.setText("Entrar");
        jButton_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_entrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_ipReuniao)
                            .addComponent(jLabel_porta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_nickname, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nickname, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(jTextField_porta)
                            .addComponent(jTextField_ipReuniao))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ipReuniao)
                    .addComponent(jTextField_ipReuniao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_porta)
                    .addComponent(jTextField_porta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nickname)
                    .addComponent(jTextField_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_ipReuniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ipReuniaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ipReuniaoActionPerformed

    private void jButton_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_entrarActionPerformed
        // TODO add your handling code here:
        
        // obtem o texto da caixa de texto e elimina espaços em branco no inicio/fim da string
        String ipLido = jTextField_ipReuniao.getText().trim();
        
        String portaLido = jTextField_porta.getText().trim();
        
        String nicknameLido = jTextField_nickname.getText().trim();
        
        // validação de dados
        int porto = 0;
        
        try{
            porto = Integer.parseInt(portaLido);
        }
        catch(NumberFormatException e){
            //80a
            JOptionPane.showMessageDialog(this, "Porta Invalida: Introduza um valor inteiro . . .");
        }
        
        // realizar validação
        if(!ipLido.isEmpty() && !nicknameLido.isEmpty()) {
            this.setVisible(false);
            mainForm.setEnabled(true);
            mainForm.ip = ipLido;
            mainForm.porta = porto;
            mainForm.nickname = nicknameLido;
            
            mainForm.setupConnection();
        }
        else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
        }
        
        
        
    }//GEN-LAST:event_jButton_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_entrar;
    private javax.swing.JLabel jLabel_ipReuniao;
    private javax.swing.JLabel jLabel_nickname;
    private javax.swing.JLabel jLabel_porta;
    private javax.swing.JTextField jTextField_ipReuniao;
    private javax.swing.JTextField jTextField_nickname;
    private javax.swing.JTextField jTextField_porta;
    // End of variables declaration//GEN-END:variables
}
